function SpawnRegions()
	return {
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "vehicle_interior", file = "media/maps/vehicle_interior/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "FortRedstone", file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "McCoysBunker", file = "media/maps/McCoysBunker/spawnpoints.lua" },
		{ name = "Hunter'sBase_map", file = "media/maps/Hunter'sBase_map/spawnpoints.lua" },
		{ name = "Rosewood VHS Store", file = "media/maps/Rosewood VHS Store/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Cryo Compound", file = "media/maps/Cryo Compound/spawnpoints.lua" },
		{ name = "TeraMart", file = "media/maps/TeraMart/spawnpoints.lua" },
		{ name = "researchbase", file = "media/maps/researchbase/spawnpoints.lua" },
		{ name = "researchbaseroad", file = "media/maps/researchbaseroad/spawnpoints.lua" },
		{ name = "AZSpawn", file = "media/maps/AZSpawn/spawnpoints.lua" },
	}
end
